using Umbraco.AI.Core.Models;

namespace Umbraco.AI.Core.Tests;

/// <summary>
/// Token usage for one model (capability, provider, model and profile combination) within a test execution.
/// </summary>
public sealed class AITestModelTokenUsage
{
    /// <summary>
    /// The capability the calls were made with (for example Chat or Embedding).
    /// </summary>
    public AICapability Capability { get; set; }

    /// <summary>
    /// The ID of the provider that served the calls, if known.
    /// </summary>
    public string? ProviderId { get; set; }

    /// <summary>
    /// The ID of the model that served the calls, if known.
    /// </summary>
    public string? ModelId { get; set; }

    /// <summary>
    /// The ID of the profile the calls resolved to, if any.
    /// </summary>
    public Guid? ProfileId { get; set; }

    /// <summary>
    /// The alias of the profile the calls resolved to, if any.
    /// </summary>
    public string? ProfileAlias { get; set; }

    /// <summary>
    /// Number of input tokens consumed by these calls.
    /// </summary>
    public int InputTokens { get; set; }

    /// <summary>
    /// Number of output tokens generated by these calls.
    /// </summary>
    public int OutputTokens { get; set; }

    /// <summary>
    /// Total tokens (input + output) for these calls. This is a lower bound when
    /// <see cref="UnreportedCallCount"/> is greater than zero.
    /// </summary>
    public int TotalTokens { get; set; }

    /// <summary>
    /// Number of tracked calls made with this model, including calls that reported no usage.
    /// </summary>
    public int CallCount { get; set; }

    /// <summary>
    /// Number of calls with this model that returned no usage details.
    /// </summary>
    public int UnreportedCallCount { get; set; }
}
